### ISSUE TITLE
Getting Invalid configuration file 'signalr.yaml' at '#/scenarios/signalr_load_test'

### ISSUE THREAD

**Issue by Shyam268** [aspnet/Benchmarks#1996]
I want to test load on webapp hosting azure signalR service i have created yaml file with content

```
profiles:
  local:
    description: "Profile for local testing"  # Added for clarity
    variables:
      serverAddress: localhost
    jobs: 
      application:
        endpoints: 
          - http://localhost:5010  # Ensure this endpoint is reachable
      load:
        endpoints: 
          - http://localhost:5010  # Ensure this endpoint is reachable

scenarios:
  signalr_load_test:
    description: "Load test for Azure Web App with Azure SignalR"
    profile: default  # Specify the profile to use for this scenario
    steps:
      - name: "Connect to SignalR Hub"
        tool: "signalr"
        command: "connect"
        arguments: "--hub-url https://web-app.azurewebsites.net/v1/signalling --connections 1000 --bearer-token Bearer token"
```

- Syntax of the file is verified and it is valid
- Agent is running on 5010 port
- Getting this error on execution  **Invalid configuration file 'signalr.yaml' at '#/scenarios/signalr_load_test'**

**Comment by sebastienros** [comment]
Looks like the file "signalr_load_test" is invalid. Have you tried to check if it's valid with an online tool? Or all the files with `--config` that you are using.

Crank should also give you a link to a local JSON file that is the result of the configuration with all the nodes evaluation and converted to JSON, but I think it should only show you that link if the original yaml file was valid.

**Comment by Shyam268** [comment]
> Looks like the file "signalr_load_test" is invalid. Have you tried to check if it's valid with an online tool? Or all the files with `--config` that you are using.
> 
> Crank should also give you a link to a local JSON file that is the result of the configuration with all the nodes evaluation and converted to JSON, but I think it should only show you that link if the original yaml file was valid.

- Verified the file content in https://www.yamllint.com/ and it is valid
-  The Command is used to execute the file is **crank --config crank.yaml --scenario signalr_load_test --profile local** and i have attached the generated json file
[crank-debug.json](https://github.com/user-attachments/files/15882996/crank-debug.json)

- Will you please help me and let me know if any valid example so that we can use to test load on web app which is hosting azure signalR service

**Comment by sebastienros** [comment]
```yaml
scenarios:
  signalr_load_test:
    description: "Load test for Azure Web App with Azure SignalR"
    profile: default  # Specify the profile to use for this scenario
    steps:
      - name: "Connect to SignalR Hub"
        tool: "signalr"
        command: "connect"
        arguments: "--hub-url https://web-app.azurewebsites.net/v1/signalling --connections 1000 --bearer-token Bearer token"
```

This is not the format of a Crank configuration file. Here is an example
https://github.com/dotnet/crank/blob/main/docs/getting_started.md#define-the-scenario

You'll find tens of other examples in the current repository under the `/scenarios` folder.
